appending_operators = ["+", "-", "x", "/"]
numbers_str = [str(e) for e in range(0, 10)]
buttons = {
    "%": None,
    "CE": None,
    "C": None,
    "<": None,
    "1/x": None,
    "x^2": None,
    "sqrt(x)": None,
    "/": "/",
    "7": "7",
    "8": "8",
    "9": "9",
    "x": "x",
    "4": "4",
    "5": "5",
    "6": "6",
    "-": "-",
    "1": "1",
    "2": "2",
    "3": "3",
    "+": "+",
    "+/-": None,
    "0": "0",
    ".": ".",
    "=": None,
}